from . import account_register_payments
from . import crm_won_lost_report
from . import custom_pop_message
from . import salesperson_wizard
from . import trafitec_cargospendientes
from . import trafitec_contrarecibo_descuentosx
from . import trafitec_cotizacion_cancelar
from . import trafitec_crm_trafico
from . import trafitec_facturas_cancelar
from . import trafitec_programacionpagosx_facturas_buscar
from . import trafitec_reportes_generales
from . import trafitec_reportes_parametros
from . import trafitec_viaje_cambiartarifa_wizard
from . import trafitec_viaje_cancelar_wizard
from . import trafitec_viaje_sinestrado_wizard