# -*- coding: utf-8 -*-

from . import account_journal
from . import account_move
from . import account_move_line
from . import account_payment
from . import amount_to_text
from . import fee_report
from . import invoice_fletex
from . import invoice_from_fletex
from . import project_task
from . import res_bank
from . import res_partner
from . import sale_order
from . import trafitec_abonos
from . import trafitec_agregar_quitar
from . import trafitec_asignaciones
from . import trafitec_buques
from . import trafitec_cancelacioncuentas
from . import trafitec_cancelacioncuentas_facturas_cliente
from . import trafitec_cancelacioncuentas_facturas_proveedor
from . import trafitec_cancelacioncuentas_relacion
from . import trafitec_cargos
from . import trafitec_cargosx
from . import trafitec_cargosx_abonos
from . import trafitec_clasificacionesg
from . import trafitec_clasificacionesgxviaje
from . import trafitec_cliente_documentos
from . import trafitec_comisiones_abono
from . import trafitec_concepto_anticipo
from . import trafitec_con_comision
from . import trafitec_con_descuentos
from . import trafitec_contrarecibo
from . import trafitec_cotizacion
from . import trafitec_cotizaciones_documentos
from . import trafitec_cotizaciones_evidencias
from . import trafitec_cotizacion_line
from . import trafitec_cotizacion_line_cargos
from . import trafitec_cotizacion_line_negociacion
from . import trafitec_cotizacion_line_origen
from . import trafitec_crm_asociados
from . import trafitec_crm_trafico
from . import trafitec_crm_trafico_pedidos
from . import trafitec_crm_trafico_registro
from . import trafitec_crm_trafico_registro_viajes
from . import trafitec_crm_trafico_resultado
from . import trafitec_crm_trafico_tablero
from . import trafitec_descuentos
from . import trafitec_descuentos_abono
from . import trafitec_etiquetas
from . import trafitec_fact_aut_cargo
from . import trafitec_fact_linea_comision
from . import trafitec_facturas_automaticas
from . import trafitec_facturas_comision
from . import trafitec_facturas_documentos
from . import trafitec_glo
from . import trafitec_lineanegocio
from . import trafitec_localidad
from . import trafitec_moviles
from . import trafitec_muelles
from . import trafitec_municipios
from . import trafitec_pagosmasivos
from . import trafitec_pagosmasivos_facturas
from . import trafitec_parametros
from . import trafitec_plazas_banxico
from . import trafitec_polizas
from . import trafitec_presupuestos
from . import trafitec_productetiqueta
from . import trafitec_producttemplate
from . import trafitec_programacionpagosx
from . import trafitec_programacionpagosx_facturas_aplicar
from . import trafitec_remolques
from . import trafitec_reportes_generales_pedidos_avance_buscar
from . import trafitec_reportes_generales_pedidos_avance_detalles
from . import trafitec_reportes_generales_pedidos_avance_resultado
from . import trafitec_reportes_generales_pedidos_avance_xdia
from . import trafitec_reportes_generales_pedidos_avance_xmes
from . import trafitec_responsable
from . import trafitec_routers
from . import trafitec_rutas
from . import trafitec_seguridad_derechos
from . import trafitec_seguridad_derechos_perfil
from . import trafitec_seguridad_perfiles
from . import trafitec_slitrack_registro
from . import trafitec_status_client
from . import trafitec_sucursal
from . import trafitec_tareas
from . import trafitec_tareas_clasificacion
from . import trafitect_contrarecibos_cargos
from . import trafitec_tipocargosadicionales
from . import trafitec_tipodoc
from . import trafitec_tipopresentacion
from . import trafitec_type_truck
from . import trafitec_ubicacion
from . import trafitec_unidades
from . import trafitec_unidadmedida
from . import trafitec_vehiculos
from . import trafitec_viaje_cargos
from . import trafitec_viajes
from . import trafitec_viajes_boletas
from . import trafitec_viajescontrarecibo
from . import trafitec_viajes_evidencias
from . import trafitec_viajes_scan
from . import fleet_vehicle
